---
title: "R Notebook"
output: html_notebook
---

```{r}
# Elég egyszer az elején behívni a package-eket
# A tidyverse része a dplyr is, meg még egy csomó más, én most a tidyverse-et töltöm be emiatt
library(tidyverse)
```

A változók átfedéseinek kiszámítása

```{r}

dataframe <- read.csv("C:/Kriszti/GitHub/lendulet_language_SL/SEM/dataframes/SEM_df.csv", header = TRUE)

overlaps = data.frame(matrix(nrow = 2809, ncol = 5))
colnames(overlaps) = c("var1", "var2", "all_overlap", "adult_overlap", "children_overlap")

n = 1

for (var1 in colnames(dataframe)[16:68])
{
  for (var2 in colnames(dataframe)[16:68])
    {
      overlaps$var1[n] = var1
      overlaps$var2[n] = var2
      overlaps$all_overlap[n] = nrow(
        dataframe %>% filter(!is.na(dataframe[,var1]) & !is.na(dataframe[,var2]))
        )
      overlaps$adult_overlap[n] = nrow(
        dataframe %>% filter(!is.na(dataframe[,var1]) & !is.na(dataframe[,var2]) & age_years > 14)
        )
      overlaps$children_overlap[n] = nrow(
        dataframe %>% filter(!is.na(dataframe[,var1]) & !is.na(dataframe[,var2]) & age_years <= 14)
        )
      n = n + 1
    }
}

```

Meg kell nézni, hogy mely változóknál van 70-nél kisebb átfedés:

```{r}

less_than_70 = overlaps %>% 
  filter(all_overlap < 70)

```


Gyanús változók?

Ha a 100-nál kevesebb átfedéssel rendelkező változókat kivesszük, akkor az érinti 
- a dichotikus hallgatási változókat,
- a PROC_SPEED_acdec változót,
- a recvoc változót,
- a SEGM_VN kezdetű változókat, 
- és a NAD változóit.

