---
title: "Demography"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
filt_df = read.csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/dataframes/filtered_SEM_df.csv")
filt_df = filt_df |>
  mutate(
    PROC_SPEED_vis_RT_med = -(PROC_SPEED_vis_RT_med),
    PROC_SPEED_ac_RT_med = -(PROC_SPEED_ac_RT_med),
    PROC_SPEED_vis_dec_RT_med = -(PROC_SPEED_vis_dec_RT_med),
    PROC_SPEED_ac_dec_RT_med = -(PROC_SPEED_ac_dec_RT_med),
    simon_RT_score = -(simon_RT_score),
    simon_ACC_score = -(simon_ACC_score),
    stroop_RT_score = -(stroop_RT_score),
    stroop_ACC_score = -(stroop_ACC_score),
    selfpaced_target_RT_diff_GP = -(selfpaced_target_RT_diff_GP),
    selfpaced_plus1_RT_diff_mellekmondat = -(selfpaced_plus1_RT_diff_mellekmondat),
    selfpaced_target_RT_diff_sertes = -(selfpaced_target_RT_diff_sertes)
  )
```

```{r}
mean(filt_df$age_years)
```

```{r}
sd(filt_df$age_years)
```

```{r}
min(filt_df$age_years)
```

```{r}
max(filt_df$age_years)
```

```{r}
filt_df %>% 
  group_by(sex) %>% 
  count()
```

```{r}
filt_df %>% 
  ggplot(aes(x = age_years, fill = sex)) +
  geom_histogram(color = "lightgrey", position = "stack", binwidth = 1.5, size = 0.25) +
  theme_minimal() +
  scale_fill_manual(values = c("#d25d7aff", "#4379aaff")) +
  scale_x_continuous(limits = c(14, 93), breaks = seq(20, 90, by = 10))
```

