---
title: "Statistical learning and language: SEM analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(lavaan)
library(broom)
library(flexplavaan)
library(influence.SEM)
```

```{r}
#df = read.csv("~/GitHub/lendulet_language_SL/SEM/dataframes/SEM_df.csv")
df = read.csv(readline("Path of dataframe (e.g., C:/experiment/df.csv): "))
df = df %>% 
  mutate(OMR_read_syls_squared = OMR_read_syls ^ 2)
df[, 17:33] = sapply(df[, 17:33], scale)
df[, 35:56] = sapply(df[, 35:56], scale)
df[, 58:75] = sapply(df[, 58:75], scale)
df = df %>% 
  filter(age_years > 14)
```

```{r}
model =
"
# latent variables
# statistical learning
SL_RT =~ SEGM_AL_medRT_TRN3_RND4 + SEGM_AL_medRT_RND4_REC5
SL_offline =~ SEGM_AL_2AFC_trigram + SEGM_AL_SEGM_prod_data + AGL_2AFC_phr + AGL_2AFC_sent + AGL_prod + SEGM_AL_2AFC_bigram
SEGM_AL_2AFC_trigram ~~ SEGM_AL_2AFC_bigram

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_1_dprime + n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ OMR_read_syls + selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
mm =~ selfpaced_plus1_RT_diff_mellekmondat
pred =~ predictive_RT_score

# dependent regression
MENYET ~ b11*nback + b12*DS + b13*PS + b14*stroop + b15*simon + b16*PS_visdec + c11*SL_RT + c12*SL_offline
reading ~ b21*nback + b22*DS + b23*PS + b24*stroop + b25*simon + b26*PS_visdec + c21*SL_RT + c22*SL_offline
pred ~ b31*nback + b32*DS + b33*PS + b34*stroop + b35*simon + b36*PS_visdec + c31*SL_RT +  c32*SL_offline
mm ~ b41*nback + b42*DS + b43*PS + b44*stroop + b45*simon + b46*PS_visdec + c41*SL_RT + c42*SL_offline
TROG ~ b51*nback + b52*DS + b53*PS + b54*stroop + b55*simon + b56*PS_visdec + c51*SL_RT + c52*SL_offline

# mediator regression
nback ~ a11*SL_RT + a12*SL_offline
DS ~ a21*SL_RT + a22*SL_offline
PS ~ a31*SL_RT + a32*SL_offline
stroop ~ a41*SL_RT + a42*SL_offline
simon ~ a51*SL_RT + a52*SL_offline
PS_visdec ~ a61*SL_RT + a62*SL_offline

# mediator residual covariance
nback ~~ DS
nback ~~ PS
nback ~~ stroop
nback ~~ simon
nback ~~ PS_visdec
DS ~~ PS
DS ~~ stroop
DS ~~ simon
DS ~~ PS_visdec
stroop ~~ PS
stroop ~~ simon
stroop ~~ PS_visdec
PS ~~ simon
PS ~~ PS_visdec
simon ~~ PS_visdec

# dependent residual covariance
MENYET ~~ reading
MENYET ~~ mm
MENYET ~~ pred
MENYET ~~ TROG
TROG ~~ reading
TROG ~~ mm
TROG ~~ pred
reading ~~ mm
reading ~~ pred
mm ~~ pred

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11
# y1 ~ x2
ind_x2_m1_y1 := a12*b11
ind_x2_m2_y1 := a22*b12
ind_x2_m3_y1 := a32*b13
ind_x2_m4_y1 := a42*b14
ind_x2_m5_y1 := a52*b15
ind_x2_m6_y1 := a62*b16
ind_x2_y1 := ind_x2_m1_y1 + ind_x2_m2_y1 + ind_x2_m3_y1 + ind_x2_m4_y1 + ind_x2_m5_y1 + ind_x2_m6_y1
tot_x2_y1 := ind_x2_y1 + c12
# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21
# y2 ~ x2
ind_x2_m1_y2 := a12*b21
ind_x2_m2_y2 := a22*b22
ind_x2_m3_y2 := a32*b23
ind_x2_m4_y2 := a42*b24
ind_x2_m5_y2 := a52*b25
ind_x2_m6_y2 := a62*b26
ind_x2_y2 := ind_x2_m1_y2 + ind_x2_m2_y2 + ind_x2_m3_y2 + ind_x2_m4_y2 + ind_x2_m5_y2 + ind_x2_m6_y2
tot_x2_y2 := ind_x2_y2 + c22
# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31
# y3 ~ x2
ind_x2_m1_y3 := a12*b31
ind_x2_m2_y3 := a22*b32
ind_x2_m3_y3 := a32*b33
ind_x2_m4_y3 := a42*b34
ind_x2_m5_y3 := a52*b35
ind_x2_m6_y3 := a62*b36
ind_x2_y3 := ind_x2_m1_y3 + ind_x2_m2_y3 + ind_x2_m3_y3 + ind_x2_m4_y3 + ind_x2_m5_y3 + ind_x2_m6_y3
tot_x2_y3 := ind_x2_y3 + c32
# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41
# y4 ~ x2
ind_x2_m1_y4 := a12*b41
ind_x2_m2_y4 := a22*b42
ind_x2_m3_y4 := a32*b43
ind_x2_m4_y4 := a42*b44
ind_x2_m5_y4 := a52*b45
ind_x2_m6_y4 := a62*b46
ind_x2_y4 := ind_x2_m1_y4 + ind_x2_m2_y4 + ind_x2_m3_y4 + ind_x2_m4_y4 + ind_x2_m5_y4 + ind_x2_m6_y4
tot_x2_y4 := ind_x2_y4 + c42
# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51
# y5 ~ x2
ind_x2_m1_y5 := a12*b51
ind_x2_m2_y5 := a22*b52
ind_x2_m3_y5 := a32*b53
ind_x2_m4_y5 := a42*b54
ind_x2_m5_y5 := a52*b55
ind_x2_m6_y5 := a62*b56
ind_x2_y5 := ind_x2_m1_y5 + ind_x2_m2_y5 + ind_x2_m3_y5 + ind_x2_m4_y5 + ind_x2_m5_y5 + ind_x2_m6_y5
tot_x2_y5 := ind_x2_y5 + c52
"
```

```{r}
model_fit = sem(model, df, missing = "ML", estimator = "ML")
```

```{r}
summary(model_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
SL_RT =
"
SL_RT =~ 1*SEGM_AL_medRT_RND4_REC5 + 1*SEGM_AL_medRT_TRN3_RND4

"
SL_RT_fit = sem(SL_RT, df, missing = "listwise")
implied_measurement(SL_RT_fit, latent = "SL_RT")
#residual_plots(SL_RT_fit, max_val = 0.01)
visualize(SL_RT_fit)
```

```{r}
SL_offline =
"
SL_offline =~ SEGM_AL_2AFC_bigram + SEGM_AL_2AFC_trigram + SEGM_AL_SEGM_prod_data + AGL_prod + AGL_2AFC_phr + AGL_2AFC_sent
#SEGM_AL_2AFC_trigram ~~ SEGM_AL_2AFC_bigram
"
SL_offline_fit = sem(SL_offline, df, missing = "listwise")
implied_measurement(SL_offline_fit, latent = "SL_offline")
residual_plots(SL_offline_fit, max_val = 0.01)
visualize(SL_offline_fit)
```

```{r}
SL_offline =
"
SL_offline =~ AGL_prod + AGL_2AFC_phr + AGL_2AFC_sent + SEGM_AL_2AFC_bigram + SEGM_AL_2AFC_trigram + SEGM_AL_SEGM_prod_data
#SEGM_AL_2AFC_trigram ~~ SEGM_AL_2AFC_bigram
"
SL_offline_fit = sem(SL_offline, df, missing = "listwise")
implied_measurement(SL_offline_fit, latent = "SL_offline")
residual_plots(SL_offline_fit, max_val = 0.01)
visualize(SL_offline_fit)
```

```{r}
PS =
"
PS =~ 1*PROC_SPEED_vis_RT_med + 1*PROC_SPEED_ac_RT_med
"
PS_fit = cfa(PS, df, missing = "listwise")
implied_measurement(PS_fit, latent = "PS")
#residual_plots(PS_fit, max_val = 0.01)
visualize(PS_fit)
```

```{r}
DS =
"
DS =~ 1*digit_span_forward_span + 1*digit_span_backward_span
"
DS_fit = sem(DS, df, missing = "listwise")
implied_measurement(DS_fit, latent = "DS")
#residual_plots(DS_fit, max_val = 0.01)
visualize(DS_fit)
```

```{r}
nback =
"
nback =~ n_back_nback_1_dprime + n_back_nback_2_dprime + n_back_nback_3_dprime
"
nback_fit = sem(nback, df, missing = "listwise")
implied_measurement(nback_fit, latent = "nback")
#residual_plots(nback_fit, max_val = 0.01)
visualize(nback_fit)
```

```{r}
read =
"
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
"
read_fit = sem(read, df, missing = "listwise")
implied_measurement(read_fit, latent = "reading")
#residual_plots(nback_fit, max_val = 0.01)
visualize(read_fit)
```

```{r}
FI = fitinfluence("cfi",model_3, df, missing = "listwise")
```

