---
title: "R Notebook"
output: html_notebook
---

---
title: "Statistical learning and language: SEM analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
library(lavaan)
library(flexplavaan)
library(semTools)
```

```{r}
# Balint
filt_df = read.csv("~/GitHub/lendulet_language_SL/SEM/dataframes/filtered_SEM_df.csv")
```

```{r}
# Kriszti
filt_df = read.csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/dataframes/filtered_SEM_df.csv")
```

```{r}
# Error variances

stroop_e = (1-0.829)*var(filt_df$stroop_RT_score, na.rm = TRUE)
simon_e = (1-0.724)*var(filt_df$simon_RT_score, na.rm = TRUE)
visdec_e = (1-0.955)*var(filt_df$PROC_SPEED_vis_dec_RT_med, na.rm = TRUE)
menyet_e = (1-0.661)*var(filt_df$MENYET_mean_ACC_all, na.rm = TRUE)
trog_e = (1-0.666)*var(filt_df$trog_pragm_ACC_mean, na.rm = TRUE)
pred_e = (1-0.866)*var(filt_df$predictive_RT_score, na.rm = TRUE)
```

First model with competing predictors of SL_RT, SL_AGL, and SL_SEGM:

```{r}
model1 =
"
# latent variables
# statistical learning
SL_RT =~ SEGM_AL_medRT_TRN3_RND4 + SEGM_AL_medRT_RND4_REC5
SL_AGL =~ AGL_2AFC_sent + AGL_prod
SL_SEGM =~ SEGM_AL_2AFC_trigram + SEGM_AL_SEGM_prod_data
#alternative
# SL_SEGM =~ SEGM_AL_2AFC_trigram + SEGM_AL_2AFC_bigram

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL_SEGM + c12*SL_RT + c13*SL_AGL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL_SEGM + c22*SL_RT + c23*SL_AGL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL_SEGM + c32*SL_RT + c33*SL_AGL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL_SEGM + c42*SL_RT + c43*SL_AGL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL_SEGM + c52*SL_RT + c53*SL_AGL

# mediator regression
stroop ~ a11*SL_SEGM + a12*SL_RT + a13*SL_AGL
PS_visdec ~ a21*SL_SEGM + a22*SL_RT + a23*SL_AGL
PS ~ a31*SL_SEGM + a32*SL_RT + a33*SL_AGL
nback ~ a41*SL_SEGM + a42*SL_RT + a43*SL_AGL
DS ~ a51*SL_SEGM + a52*SL_RT + a53*SL_AGL
simon ~ a61*SL_SEGM + a62*SL_RT + a63*SL_AGL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y1 ~ x2
ind_x2_m1_y1 := a12*b11
ind_x2_m2_y1 := a22*b12
ind_x2_m3_y1 := a32*b13
ind_x2_m4_y1 := a42*b14
ind_x2_m5_y1 := a52*b15
ind_x2_m6_y1 := a62*b16
ind_x2_y1 := ind_x2_m1_y1 + ind_x2_m2_y1 + ind_x2_m3_y1 + ind_x2_m4_y1 + ind_x2_m5_y1 + ind_x2_m6_y1
tot_x2_y1 := ind_x2_y1 + c12

# y1 ~ x3
ind_x3_m1_y1 := a13*b11
ind_x3_m2_y1 := a23*b12
ind_x3_m3_y1 := a33*b13
ind_x3_m4_y1 := a43*b14
ind_x3_m5_y1 := a53*b15
ind_x3_m6_y1 := a63*b16
ind_x3_y1 := ind_x3_m1_y1 + ind_x3_m2_y1 + ind_x3_m3_y1 + ind_x3_m4_y1 + ind_x3_m5_y1 + ind_x3_m6_y1
tot_x3_y1 := ind_x3_y1 + c13

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y2 ~ x2
ind_x2_m1_y2 := a12*b21
ind_x2_m2_y2 := a22*b22
ind_x2_m3_y2 := a32*b23
ind_x2_m4_y2 := a42*b24
ind_x2_m5_y2 := a52*b25
ind_x2_m6_y2 := a62*b26
ind_x2_y2 := ind_x2_m1_y2 + ind_x2_m2_y2 + ind_x2_m3_y2 + ind_x2_m4_y2 + ind_x2_m5_y2 + ind_x2_m6_y2
tot_x2_y2 := ind_x2_y2 + c22

# y2 ~ x3
ind_x3_m1_y2 := a13*b21
ind_x3_m2_y2 := a23*b22
ind_x3_m3_y2 := a33*b23
ind_x3_m4_y2 := a43*b24
ind_x3_m5_y2 := a53*b25
ind_x3_m6_y2 := a63*b26
ind_x3_y2 := ind_x3_m1_y2 + ind_x3_m2_y2 + ind_x3_m3_y2 + ind_x3_m4_y2 + ind_x3_m5_y2 + ind_x3_m6_y2
tot_x3_y2 := ind_x3_y2 + c23

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y3 ~ x2
ind_x2_m1_y3 := a12*b31
ind_x2_m2_y3 := a22*b32
ind_x2_m3_y3 := a32*b33
ind_x2_m4_y3 := a42*b34
ind_x2_m5_y3 := a52*b35
ind_x2_m6_y3 := a62*b36
ind_x2_y3 := ind_x2_m1_y3 + ind_x2_m2_y3 + ind_x2_m3_y3 + ind_x2_m4_y3 + ind_x2_m5_y3 + ind_x2_m6_y3
tot_x2_y3 := ind_x2_y3 + c32

# y3 ~ x3
ind_x3_m1_y3 := a13*b31
ind_x3_m2_y3 := a23*b32
ind_x3_m3_y3 := a33*b33
ind_x3_m4_y3 := a43*b34
ind_x3_m5_y3 := a53*b35
ind_x3_m6_y3 := a63*b36
ind_x3_y3 := ind_x3_m1_y3 + ind_x3_m2_y3 + ind_x3_m3_y3 + ind_x3_m4_y3 + ind_x3_m5_y3 + ind_x3_m6_y3
tot_x3_y3 := ind_x3_y3 + c33

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y4 ~ x2
ind_x2_m1_y4 := a12*b41
ind_x2_m2_y4 := a22*b42
ind_x2_m3_y4 := a32*b43
ind_x2_m4_y4 := a42*b44
ind_x2_m5_y4 := a52*b45
ind_x2_m6_y4 := a62*b46
ind_x2_y4 := ind_x2_m1_y4 + ind_x2_m2_y4 + ind_x2_m3_y4 + ind_x2_m4_y4 + ind_x2_m5_y4 + ind_x2_m6_y4
tot_x2_y4 := ind_x2_y4 + c42

# y4 ~ x3
ind_x3_m1_y4 := a13*b41
ind_x3_m2_y4 := a23*b42
ind_x3_m3_y4 := a33*b43
ind_x3_m4_y4 := a43*b44
ind_x3_m5_y4 := a53*b45
ind_x3_m6_y4 := a63*b46
ind_x3_y4 := ind_x3_m1_y4 + ind_x3_m2_y4 + ind_x3_m3_y4 + ind_x3_m4_y4 + ind_x3_m5_y4 + ind_x3_m6_y4
tot_x3_y4 := ind_x3_y4 + c43

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# y5 ~ x2
ind_x2_m1_y5 := a12*b51
ind_x2_m2_y5 := a22*b52
ind_x2_m3_y5 := a32*b53
ind_x2_m4_y5 := a42*b54
ind_x2_m5_y5 := a52*b55
ind_x2_m6_y5 := a62*b56
ind_x2_y5 := ind_x2_m1_y5 + ind_x2_m2_y5 + ind_x2_m3_y5 + ind_x2_m4_y5 + ind_x2_m5_y5 + ind_x2_m6_y5
tot_x2_y5 := ind_x2_y5 + c52

# y5 ~ x3
ind_x3_m1_y5 := a13*b51
ind_x3_m2_y5 := a23*b52
ind_x3_m3_y5 := a33*b53
ind_x3_m4_y5 := a43*b54
ind_x3_m5_y5 := a53*b55
ind_x3_m6_y5 := a63*b56
ind_x3_y5 := ind_x3_m1_y5 + ind_x3_m2_y5 + ind_x3_m3_y5 + ind_x3_m4_y5 + ind_x3_m5_y5 + ind_x3_m6_y5
tot_x3_y5 := ind_x3_y5 + c53

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model1_fit = sem(model1, filt_df, missing = "ML", estimator = "MLR")
```

```{r}
summary(model1_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

Second model with only SL_RT as predictor:

```{r}
model_SL_RT =
"
# latent variables
# statistical learning
SL_RT =~ SEGM_AL_medRT_TRN3_RND4 + SEGM_AL_medRT_RND4_REC5

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL_RT
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL_RT
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL_RT
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL_RT
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL_RT

# mediator regression
stroop ~ a11*SL_RT
PS_visdec ~ a21*SL_RT
PS ~ a31*SL_RT
nback ~ a41*SL_RT
DS ~ a51*SL_RT
simon ~ a61*SL_RT

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_SL_RT = sem(model_SL_RT, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_SL_RT, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

Next we run several models with different statistical learning variables as predictors.

AGL_sent:

```{r}
model_AGL_sent =
"
# latent variables
# statistical learning
SL =~ AGL_2AFC_sent

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_AGL_sent = sem(model_AGL_sent, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_AGL_sent, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

AGL_prod:

```{r}
model_AGL_prod =
"
# latent variables
# statistical learning
SL =~ AGL_prod

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51
"
```

```{r}
model_fit_AGL_prod = sem(model_AGL_prod, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_AGL_prod, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

AGL_phrase

```{r}
model_AGL_phr =
"
# latent variables
# statistical learning
SL =~ AGL_2AFC_phr

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51


# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_AGL_phr = sem(model_AGL_phr, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_AGL_phr, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

SEGM_AL_SEGM_prod_data

```{r}
model_SEGM_prod =
"
# latent variables
# statistical learning
SL =~ SEGM_AL_SEGM_prod_data

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_SEGM_prod = sem(model_SEGM_prod, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_SEGM_prod, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

SEGM_AL_2AFC_trigram:

```{r}
model_SEGM_trigram =
"
# latent variables
# statistical learning
SL =~ SEGM_AL_2AFC_trigram

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_SEGM_trigram = sem(model_SEGM_trigram, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_SEGM_trigram, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

SEGM_AL_2AFC_bigram:

```{r}

model_SEGM_bigram =
"
# latent variables
# statistical learning
SL =~ SEGM_AL_2AFC_bigram

# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
TROG =~ trog_pragm_ACC_mean
reading =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
pred =~ predictive_RT_score
OMR =~ OMR_read_syls

# dependent regression
TROG ~ b11*stroop + b12*PS_visdec + b13*PS + b14*nback + b15*DS + b16*simon + c11*SL
MENYET ~ b21*stroop + b22*PS_visdec + b23*PS + b24*nback + b25*DS + b26*simon + c21*SL
reading ~ b31*stroop + b32*PS_visdec + b33*PS + b34*nback + b35*DS + b36*simon + c31*SL
pred ~ b41*stroop + b42*PS_visdec + b43*PS + b44*nback + b45*DS + b46*simon + c41*SL
OMR ~ b51*stroop + b52*PS_visdec + b53*PS + b54*nback + b55*DS + b56*simon + c51*SL

# mediator regression
stroop ~ a11*SL
PS_visdec ~ a21*SL
PS ~ a31*SL
nback ~ a41*SL
DS ~ a51*SL
simon ~ a61*SL

# mediator residual covariance
stroop ~~ PS_visdec
stroop ~~ PS
PS_visdec ~~ PS
stroop ~~ nback
PS_visdec ~~ nback
PS ~~ nback
stroop ~~ DS
PS_visdec ~~ DS
PS ~~ DS
nback ~~ DS
stroop ~~ simon
PS_visdec ~~ simon
PS ~~ simon
nback ~~ simon
DS ~~ simon

# dependent residual covariance
TROG ~~ MENYET
TROG ~~ reading
MENYET ~~ reading
TROG ~~ pred
MENYET ~~ pred
reading ~~ pred
TROG ~~ OMR
MENYET ~~ OMR
reading ~~ OMR
pred ~~ OMR

# effect decomposition
# y1 ~ x1
ind_x1_m1_y1 := a11*b11
ind_x1_m2_y1 := a21*b12
ind_x1_m3_y1 := a31*b13
ind_x1_m4_y1 := a41*b14
ind_x1_m5_y1 := a51*b15
ind_x1_m6_y1 := a61*b16
ind_x1_y1 := ind_x1_m1_y1 + ind_x1_m2_y1 + ind_x1_m3_y1 + ind_x1_m4_y1 + ind_x1_m5_y1 + ind_x1_m6_y1
tot_x1_y1 := ind_x1_y1 + c11

# y2 ~ x1
ind_x1_m1_y2 := a11*b21
ind_x1_m2_y2 := a21*b22
ind_x1_m3_y2 := a31*b23
ind_x1_m4_y2 := a41*b24
ind_x1_m5_y2 := a51*b25
ind_x1_m6_y2 := a61*b26
ind_x1_y2 := ind_x1_m1_y2 + ind_x1_m2_y2 + ind_x1_m3_y2 + ind_x1_m4_y2 + ind_x1_m5_y2 + ind_x1_m6_y2
tot_x1_y2 := ind_x1_y2 + c21

# y3 ~ x1
ind_x1_m1_y3 := a11*b31
ind_x1_m2_y3 := a21*b32
ind_x1_m3_y3 := a31*b33
ind_x1_m4_y3 := a41*b34
ind_x1_m5_y3 := a51*b35
ind_x1_m6_y3 := a61*b36
ind_x1_y3 := ind_x1_m1_y3 + ind_x1_m2_y3 + ind_x1_m3_y3 + ind_x1_m4_y3 + ind_x1_m5_y3 + ind_x1_m6_y3
tot_x1_y3 := ind_x1_y3 + c31

# y4 ~ x1
ind_x1_m1_y4 := a11*b41
ind_x1_m2_y4 := a21*b42
ind_x1_m3_y4 := a31*b43
ind_x1_m4_y4 := a41*b44
ind_x1_m5_y4 := a51*b45
ind_x1_m6_y4 := a61*b46
ind_x1_y4 := ind_x1_m1_y4 + ind_x1_m2_y4 + ind_x1_m3_y4 + ind_x1_m4_y4 + ind_x1_m5_y4 + ind_x1_m6_y4
tot_x1_y4 := ind_x1_y4 + c41

# y5 ~ x1
ind_x1_m1_y5 := a11*b51
ind_x1_m2_y5 := a21*b52
ind_x1_m3_y5 := a31*b53
ind_x1_m4_y5 := a41*b54
ind_x1_m5_y5 := a51*b55
ind_x1_m6_y5 := a61*b56
ind_x1_y5 := ind_x1_m1_y5 + ind_x1_m2_y5 + ind_x1_m3_y5 + ind_x1_m4_y5 + ind_x1_m5_y5 + ind_x1_m6_y5
tot_x1_y5 := ind_x1_y5 + c51

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
predictive_RT_score ~~ 0.136*predictive_RT_score
"
```

```{r}
model_fit_SEGM_bigram = sem(model_SEGM_bigram, filt_df, missing = "ML", estimator = "MLR")
summary(model_fit_SEGM_bigram, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
model_fit_AGL_phr_2 = sem(model_AGL_sent, filt_df, missing = "listwise")
implied_measurement(model_fit_AGL_phr_2, latent = "SL")
#residual_plots(DS_fit, max_val = 0.01)
visualize(model_fit_AGL_phr_2)
```


