---
title: "CFA of 14YO+ participants vs. all participants with indices n>100"
output: html_notebook
---

```{r}
library(tidyverse)
library(lavaan)
library(semTools)
library(broom)
```

```{r}
#df <- read.csv("~/GitHub/lendulet_language_SL/SEM/dataframes/SEM_df.csv")
df = read.csv(readline("Path of dataframe (e.g., C:/experiment/df.csv): "))
df = df %>% 
  filter(age_years > 14)
df[, 17:33] = sapply(df[, 17:33], scale)
df[, 35:56] = sapply(df[, 35:56], scale)
df[, 58:74] = sapply(df[, 58:74], scale)
```

# 1. Statistical learning measures

```{r}
SL_model =
  "
  SL_RT =~ SEGM_AL_medRT_TRN3_RND4 + SEGM_AL_medRT_RND4_REC5
  SL_ACC =~ 1*SEGM_AL_ACC_RND4_REC5 + 1*SEGM_AL_ACC_TRN3_RND4
  SL_offline =~ SEGM_AL_2AFC_trigram + SEGM_AL_SEGM_prod_data + AGL_2AFC_phr + AGL_2AFC_sent + AGL_prod
  "
```

```{r}
SL_fit = cfa(SL_model, df, missing = "ML", estimator = "ML")
```

```{r}
summary(SL_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

# 2. General cognitive measures

```{r}
CG_model =
  "
  PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
  DS =~ digit_span_forward_span + digit_span_backward_span
  nback =~ n_back_nback_1_dprime + n_back_nback_2_dprime + n_back_nback_3_dprime
  "
```

```{r}
CG_fit = cfa(CG_model, df, missing = "ML", estimator = "ML")
```

```{r}
summary(CG_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

# 3. Language measures

```{r}
LA_model =
  "
  offline =~ MENYET_mean_ACC_all + trog_pragm_ACC_mean
  reading =~ OMR_read_syls + selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
  "
```

```{r}
LA_fit = cfa(LA_model, df, missing = "ML", estimator = "ML")
```

```{r}
summary(LA_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```
