---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
library(lavaan)
library(flexplavaan)
library(semTools)
```

```{r}
# Balint
filt_df = read.csv("~/GitHub/lendulet_language_SL/SEM/dataframes/filtered_SEM_df.csv")
```

```{r}
# Kriszti
filt_df = read.csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/dataframes/filtered_SEM_df.csv")
```

```{r}
# Error variances

stroop_e = (1-0.829)*var(filt_df$stroop_RT_score, na.rm = TRUE)
simon_e = (1-0.724)*var(filt_df$simon_RT_score, na.rm = TRUE)
visdec_e = (1-0.955)*var(filt_df$PROC_SPEED_vis_dec_RT_med, na.rm = TRUE)
menyet_e = (1-0.661)*var(filt_df$MENYET_mean_ACC_all, na.rm = TRUE)
pred_e = (1-0.866)*var(filt_df$predictive_RT_score, na.rm = TRUE)
trog_e = (1-0.666)*var(filt_df$trog_pragm_ACC_mean, na.rm = TRUE)
```


```{r}

model_DS = 

"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# DS on outcome 
MENYET ~ b11*DS
pred ~ b21*DS
space ~ b31*DS
OMR ~ b41*DS
TROG ~ b51*DS

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"

model_simon = 
"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# Simon on outcome 
MENYET ~ b11*simon
pred ~ b21*simon
space ~ b31*simon
OMR ~ b41*simon
TROG ~ b51*simon

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"

model_PS_visdec = 
"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# PS_visdec on outcome 
MENYET ~ b11*PS_visdec
pred ~ b21*PS_visdec
space ~ b31*PS_visdec
OMR ~ b41*PS_visdec
TROG ~ b51*PS_visdec

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"

model_nback = 
"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# nback on outcome 
MENYET ~ b11*nback
pred ~ b21*nback
space ~ b31*nback
OMR ~ b41*nback
TROG ~ b51*nback

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"

model_PS =
  
"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# PS on outcome 
MENYET ~ b11*PS
pred ~ b21*PS
space ~ b31*PS
OMR ~ b41*PS
TROG ~ b51*PS

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"

model_stroop = 
  
"
# cognitive
PS =~ PROC_SPEED_vis_RT_med + PROC_SPEED_ac_RT_med
DS =~ digit_span_forward_span + digit_span_backward_span
nback =~ n_back_nback_2_dprime + n_back_nback_3_dprime
stroop =~ stroop_RT_score
simon =~ simon_RT_score
PS_visdec =~ PROC_SPEED_vis_dec_RT_med

# language
MENYET =~ MENYET_mean_ACC_all
pred =~ predictive_RT_score
space =~ selfpaced_target_RT_diff_GP + selfpaced_target_RT_diff_sertes
OMR =~ OMR_read_syls
TROG =~ trog_pragm_ACC_mean

# Stroop on outcome 
MENYET ~ b11*stroop
pred ~ b21*stroop
space ~ b31*stroop
OMR ~ b41*stroop
TROG ~ b51*stroop

# dependent residual covariance
MENYET ~~ pred
MENYET ~~ space
pred ~~ space
MENYET ~~ OMR
pred ~~ OMR
space ~~ OMR
TROG ~~ MENYET
TROG ~~ space
TROG ~~ pred
TROG ~~ OMR

# single indicator factors

stroop_RT_score ~~ 0.152*stroop_RT_score
simon_RT_score ~~ 0.274*simon_RT_score
PROC_SPEED_vis_dec_RT_med ~~ 0.043*PROC_SPEED_vis_dec_RT_med
MENYET_mean_ACC_all ~~ 0.334*MENYET_mean_ACC_all
predictive_RT_score ~~ 0.136*predictive_RT_score
trog_pragm_ACC_mean ~~ 0.326*trog_pragm_ACC_mean
"
```

```{r}
model_DS_fit = sem(model_DS, filt_df, missing = "ML", estimator = "MLR")
model_simon_fit = sem(model_simon, filt_df, missing = "ML", estimator = "MLR")
model_PS_fit = sem(model_PS, filt_df, missing = "ML", estimator = "MLR")
model_PS_visdec_fit = sem(model_PS_visdec, filt_df, missing = "ML", estimator = "MLR")
model_stroop_fit = sem(model_stroop, filt_df, missing = "ML", estimator = "MLR")
model_nback_fit = sem(model_nback, filt_df, missing = "ML", estimator = "MLR")
```

```{r}
summary(model_DS_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
summary(model_simon_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
summary(model_PS_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
summary(model_PS_visdec_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
summary(model_stroop_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```

```{r}
summary(model_nback_fit, standardized = TRUE, rsquare = TRUE, fit.measures = TRUE)
```
