---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
library(psych)
```

```{r}
# Balint
```

```{r}
# Kriszti
AGL_2AFC_phr = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/AGL_2AFC_phr.csv")
AGL_2AFC_sent = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/AGL_2AFC_sent.csv")
AGL_prod = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/AGL_prod.csv")
MENYET = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/MENYET.csv")
SEGM_AL_2AFC_trigram = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/SEGM_AL_2AFC_trigram.csv")
SEGM_AL_SEGM_prod_data = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/SEGM_AL_SEGM_prod_data.csv")
selfpaced_target_RT_diff_GP = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/selfpaced_target_RT_diff_GP.csv")
selfpaced_target_RT_diff_sertes = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/selfpaced_target_RT_diff_sertes.csv")
TROG = read_csv("C:/Users/Kriszti/GitHub/lendulet_language_SL/SEM/reliability_testing_SEM_post_hoc/dataframes/TROG.csv")
```

```{r}
o1 = omega(AGL_2AFC_phr[,-1], nfactors = 1, flip = FALSE)
o2 = omega(AGL_2AFC_sent[,-1], nfactors = 1, flip = FALSE)
o3 = omega(AGL_prod[,-1], nfactors = 1, flip = FALSE)
o4 = omega(MENYET[,-1], nfactors = 1, flip = FALSE)
o5 = omega(SEGM_AL_2AFC_trigram[,-1], nfactors = 1, flip = FALSE)
o6 = omega(SEGM_AL_SEGM_prod_data[,-1], nfactors = 1, flip = FALSE)
o7 = omega(selfpaced_target_RT_diff_GP[,-1], nfactors = 1, flip = FALSE)
o8 = omega(selfpaced_target_RT_diff_sertes[,-1], nfactors = 1, flip = FALSE)
o9 = omega(TROG[,-1], nfactors = 1, flip = FALSE)
```


